### ISSUE TITLE
Feature Request: Add info about full friendly URLs

### ISSUE THREAD

**Issue by NikolayShapovalovMoto** [xfrocks/docker-xenforo#4]
Thanks a lot for docker image.
It takes me some time to enable "full friendly URLs"
I use php apache image and found that there are no mod_rewrite inside.
I found that I should use "FallbackResource /index.php" hhttps://github.com/xfrocks/docker-xenforo/blob/master/php-apache/build.sh#L56.
After I add to .htaccess it in the end, "full friendly URLs" start to work.
I propose to add info about it to README.

**Comment by daohoangson** [comment]
I have added the note, thank you for the suggestion.
